# Generated by Django 4.2.1 on 2023-05-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Número da Mesa'),
        ),
    ]
