# Generated by Django 4.2.1 on 2023-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_add_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='key',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número da Mesa'),
        ),
    ]
