# Generated by Django 4.2.1 on 2023-06-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_table_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='key',
            new_name='verification_code',
        ),
    ]
