# Generated by Django 4.2.1 on 2023-06-06 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0004_rename_key_table_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='users',
            field=models.ManyToManyField(blank=True, editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
