# Generated by Django 4.2.1 on 2023-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_table_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='verification_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Código de Verificação'),
        ),
    ]
