# Generated by Django 4.2.1 on 2023-06-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_table_users'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('item_name', models.CharField(max_length=100, verbose_name='Nome do Prato/Produto')),
                ('item_id', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='table.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, editable=False, to='order.orderitem'),
        ),
    ]
