# Generated by Django 4.2.1 on 2023-06-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_remove_order_items_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
