# Generated by Django 4.2.1 on 2023-05-28 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Restaurante')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('cnpj', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[0-9]{14}$', 'CNPJ inválido!')], verbose_name='CNPJ')),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]{8}$', 'CEP inválido!')], verbose_name='CEP')),
                ('address_line1', models.CharField(max_length=100, verbose_name='Endereço 1')),
                ('address_line2', models.CharField(blank=True, max_length=100, verbose_name='Endereço 2 (Opcional)')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('ac', 'AC'), ('al', 'AL'), ('ap', 'AP'), ('am', 'AM'), ('ba', 'BA'), ('ce', 'CE'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mt', 'MT'), ('ms', 'MS'), ('mg', 'MG'), ('pa', 'PA'), ('pb', 'PB'), ('pr', 'PR'), ('pe', 'PE'), ('pi', 'PI'), ('rj', 'RJ'), ('rn', 'RN'), ('rs', 'RS'), ('ro', 'RO'), ('rr', 'RR'), ('sc', 'SC'), ('sp', 'SP'), ('se', 'SE'), ('to', 'TO'), ('df', 'DF')], max_length=2, verbose_name='Estado')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, message='O telefone deve ter no mínimo 11 dígitos, incluindo o DDD.'), django.core.validators.MaxLengthValidator(11, message='O telefone deve ter no máximo 11 dígitos, incluindo o DDD.')], verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['id'],
            },
        ),
    ]
